個別のURLで各キャラクターのモーダルに飛べるようにした
VOICEVOX/voicevox_blog pull request #102
Opened 2022-10-16 08:55 UTC by k-chop

## 内容
- `/dormitory/ずんだもん` のようなURLでアクセスすると個別のキャラ紹介モーダルが出るようにしました。
- ボイボ寮のページからモーダルを開いたときも `history.replaceState()` でURLが書き換わります。
   - （twitter共有ボタンみたいなのがあった方がいいんでしょうか）
   - モーダルを閉じたらURLは `/dormitory` に戻ります。
- OGPもとりあえず追加してみましたが、表示確認はできていません
- SSGで各キャラクターページのhtmlファイルが増えるだけなので、デプロイも恐らく・・・問題ないと思います

## 関連issue
close #79 

## 方法
- [createPages](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#createPages) で各自のページを生成するようにしました。どのページも中身は全部 `pages/dormitory.tsx` です。
- URLは `characterInfos` の `name` 定義を用いて日本語URLにしています
   - `characterKeys` だともち子さんのURLが `/dormitory/モチノキョウコ` になってしまうため

## 動作イメージ
![Animation456](https://user-images.githubusercontent.com/241973/196026897-73226051-86b2-41f2-b368-553661446576.gif)

## 動作確認
- `npm run build && npm run serve` で動作確認
- ✅ すべてのキャラクターのURLが開けることを確認
- ✅ ボイボ寮ページからモーダルを開閉したときURLが変わることを確認

## 確認したいこと
- **日本語URLで大丈夫かどうか？**
   - URLを張るときはurl encodeされていると思うのでぱっと見何のURLか分かりづらそう
      - ただしOGPがあればtwitter等での共有時はそちらが表示されるので特に問題はなさそう
   - コピペミス等でリンクにならないと悲しい
      - 手元の環境ではブラウザのアドレスバーに表示された日本語URLをtwitterにコピペすると勝手にurl encodeされているようですが、スマホや他の環境では不明
   - 連番や適当なidに変えることは簡単ですが、その場合identifier -> characterKeyのmapが必要になります
      - 新キャラ追加時の更新箇所が増える
- **OGPの有無**
   - 割と簡単に追加できそうだったので入れてみたのですが、ローカルでは表示確認できず
   - 将来的に、とのことだったので現時点では入れなくてよい場合は消しておきます！

2022-10-16 08:57 UTC, k-chop commented on gatsby-node.ts
> +export const createPages: GatsbyNode["createPages"] = async ({ actions }) => {
commonjsだとcharacterKeysをimport/requireで読み込めなかったため
ts + esmにしてimportしました

gatsby 4.9からtypescriptでの設定ファイル記述に対応しているようです
https://www.coppla-note.net/posts/gatsby/convert-typescript/

2022-10-16 08:59 UTC, k-chop commented on src/contexts/context.ts
> +  "ずんだもん",
設定ファイル側に同じ記述が増えるのを防ぎたかったのでexportして使うようにしました

2022-10-16 09:02 UTC, k-chop commented on src/pages/dormitory.tsx
> +  }, [showingCharacterModal])
class名付け替えは元はイベントハンドラ内で実行していましたが、
最初からモーダル開いている場合に実行し損ねていたのでuseEffectにしました

2022-10-16 09:04 UTC, k-chop commented on src/pages/dormitory.tsx
> +          image={initialSelectedCharacterInfo?.bustupImage.images.fallback?.src}
とりあえず追加した個別ページの場合のOGP設定です。
画像はキャラクターカードで表示されるバストアップ画像を指定しました

2022-10-16 09:08 UTC, k-chop commented on src/pages/dormitory.tsx
> +        initialSelectedCharacterKey={initialSelectedCharacterKey}
```
/dormitory           -> { initialSelectedCharacterKey: undefined }
/dormitory/ずんだもん -> { initialSelectedCharacterKey: "ずんだもん" }
```
こんな感じでここにcharacterKeyが入ってきます

2022-10-16 12:40 UTC, Hiroshiba commented
おお！！！！良いですね！！！！！
まだPR一切見れてないのですが、日本語URLではなくキャラごとにidを振る形式にできればと思います！

idをリスト化してみました！基本的に「読み」部分をsnake_caseで書く形にしようかなと思います。
```
四国めたん: shikoku_metan
ずんだもん: zundamon
春日部つむぎ: kasukabe_tsumugi
波音リツ: namine_ritsu
玄野武宏: kurono_takehiro
白上虎太郎: shirakami_kotaro
青山龍星: aoyama_ryusei
冥鳴ひまり: meimei_himari
九州そら: kyushu_sora
もち子さん: mochikosan
剣崎雌雄: kenzaki_mesuo
WhiteCUL: white_cul
後鬼: goki
No.7: number_seven
```

もしよければこちらを使う形にするのもお願いできると嬉しいです･･･！
ご面倒でしたらあとで変えてみます。

たしか今は本名がキーのobjectにデータが含まれてる形ですよね。
本来はまあidをキーにして本名がデータに有るべきですが、idをキーにすると変更が大きくなりそうなので、とりあえず本名がキーでobjectの中にidがある形だと変更が少なくなるのかなと思いました！

```
モチノキョウコ: {
  id: mochikosan,
}
```

2022-10-16 14:07 UTC, k-chop commented
なるほど、別途map用意しなくてもcharacterInfosに持たせてしまえば良いですね！
id振る形で了解です、修正します 👍

2022-10-16 14:56 UTC, k-chop commented
[e16c5e4](https://github.com/VOICEVOX/voicevox_blog/pull/102/commits/e16c5e4306863c55be074e8e12291b470f52697b) でidがページURLになるようにしました！合わせてPR本文を少し差し替えています。

gatsbyの `createPages` apiを叩くのは `src/pages/domitory.tsx` がrenderされる前なので、`src/contexts/context.ts` の方のcharacterInfosにもid追加しています。
2ヶ所に出てきてちょっと微妙ですが、idがcharacterInfosのキーになれば解消しそう...（そのうち着手してみようと思います）

2022-10-16 17:07 UTC, Hiroshiba requested changes
すごくわかりやすかったです！！
いくつか変更をお願いしたいのでRequest changesになっていますが、ほぼLGTMの気持ちです！！

2022-10-16 17:07 UTC, Hiroshiba commented on gatsby-node.ts
> +  characterKeys.forEach(key => {
なるほど、gatsbyはページ作成をglobalなここに書くしかない感じなんですね！
（欲を言えば`pages/domitory.tsx`に書きたいけど、全キャラ分のtsxファイルを作るしかないんだろうなーと）

増えてくるとなんのページを作っているかわからなくなりそうだなとちょっと思いました！
ということでこんな感じのコメントだけ･･･！
```suggestion
  // ボイボ寮のキャラクターごとのURL
  characterKeys.forEach(key => {
```

2022-10-16 17:07 UTC, Hiroshiba commented on src/contexts/context.ts
> +  "ずんだもん",
なんとなくcontextsディレクトリはreactのcontextが入るものという感じで作っていたので、こういったglobal情報を定義するファイルのディレクトリを別で作っても良いかもと思いました！

webフロントにあまり明るくないのですが、どういう名前がいいのでしょう･･･。`defines`･･･？
（変更はこのPR内じゃなくてもいいかなと思っています）

2022-10-16 17:07 UTC, Hiroshiba commented on src/pages/dormitory.tsx
> +      id: "shirakami_kotaro",
迷ったのですが、`kotarou`に変更でお願いします 🙇‍♂️ 
```suggestion
      id: "shirakami_kotarou",
```
（ふりがなが同じ母音が２回続くときだけ略すというルールにしようかなと･･･。）

2022-10-16 17:07 UTC, Hiroshiba commented on src/pages/dormitory.tsx
> +  }, [showingCharacterModal])
素晴らしいです、ありがとうございます！！

2022-10-16 17:07 UTC, Hiroshiba commented on src/pages/dormitory.tsx
> +    window.history.replaceState({}, "", `/dormitory/${url}`)
細かいですがurlは`https://~`のイメージがあるのでこうかなと！
```suggestion
    const characterId = characterInfos[characterKey]?.id
    window.history.replaceState({}, "", `/dormitory/${characterId}`)
```

2022-10-16 17:07 UTC, Hiroshiba commented on src/pages/dormitory.tsx
> +        />
ちょっとどちらにすべきか難しいのと常識がわからないのですが、`initial`ではない`selectedCharacterKey`の`CharacterInfo`から情報を取ってたほうが直感に合うかもと思いました！

別のキャラを開いた状態でHTMLを見た時、そのキャラの情報が書かれていたほうが直感的かなと思った次第です。
ただ寮生ページで`selectedCharacterKey == initialSelectedCharacterKey`となっているのかは知識がなくわからないです･･･。

2022-10-17 03:54 UTC, k-chop commented on gatsby-node.ts
> +  characterKeys.forEach(key => {
https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#collection-routes
collection routesという機能があるので、
`pages/domitory/{Character.id}.tsx` というファイルを1つ作れば全キャラ分のtsxを作らずにいけると思います。
が、graphqlにcharacterInfos（の一部）を乗せる必要があるようです。

yamlかjsonに書いて読み込めばよさそう...？
https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-json-or-yaml/

直すのは全然大丈夫なので、この方針で問題なければ書き直そうと思います 👍

2022-10-17 03:55 UTC, k-chop commented on gatsby-node.ts
> +  characterKeys.forEach(key => {
ちなみに `pages/domitory.tsx` 自体に出し分けを書くのは、OGPが必要なら不可能です。
twitterやfacebookのOGPクローラはjsを実行してくれないので、
react-helmetで動的にogpタグ設定しても読んでくれません。

なのでビルド時にキャラクターの数だけhtmlを書き出すアプローチになりますが、
その場合createPagesもしくはcollection routesの形で
gatsbyに「これらのデータ使ってhtml出力するぞ」とどこかで伝える必要があり、
それはコンポーネント定義内には書けない、という感じですね

なおgatsbyエアプなので適当なことを言ってたらすみません

2022-10-17 03:59 UTC, k-chop commented
（なぜかコメント返信できなくなっていたので引用返信）

> なんとなくcontextsディレクトリはreactのcontextが入るものという感じで作っていたので、こういったglobal情報を定義するファイルのディレクトリを別で作っても良いかもと思いました！

たしかに！
pathは `src/constants.ts` か `src/constants/characters.ts` がよくある感じな気がします。

2022-10-17 04:00 UTC, k-chop commented on src/pages/dormitory.tsx
> +      id: "shirakami_kotaro",
了解です！suggest取り込ませていただきました

2022-10-17 04:09 UTC, k-chop commented on src/pages/dormitory.tsx
> +        />
> 別のキャラを開いた状態でHTMLを見た時、そのキャラの情報が書かれていたほうが直感的

あ、これは気付いていませんでした、ありがとうございます！！
現状だと `/domitory/zundamon` を開いたあとにモーダル閉じてめたんちゃんのキャラ紹介を開いても、ずんだもんのままになってますね。
Seoコンポーネント内でhtmlのtitleも設定していたのでこれは変えないと...

> ただ寮生ページで～

setStateに初期値として与えているので `初期値のselectedCharacterKey == initialSelectedCharacterKey` であってます！

2022-10-17 04:14 UTC, k-chop commented
- （判断待ち）createPages APIは使わずcollection routesを使う
- characterKeys, characterInfosをconstantsに移す
   - collection routesに移すならgraphqlに乗せるので不要になるかも？
- Seoコンポーネントの引数を直す

という感じで修正しようと思います、ちょっと忙しく2,3日かかるかもしれません 🙇

2022-10-17 15:49 UTC, Hiroshiba commented on gatsby-node.ts
> +  characterKeys.forEach(key => {
> collection routesという機能があるので、`pages/domitory/{Character.id}.tsx`というファイルを1つ作れば

おお！！！！存じませんでした。
メンテナンスがちょっとしやすそうな印象を受けました。

> が、graphqlにcharacterInfos（の一部）を乗せる必要があるようです。
> yamlかjsonに書いて読み込めばよさそう...？

あーー･･･。
別にjsonやyamlに書くと型が消えちゃって、タイポしてても気づかないんですよね･･･。
もし`.ts`かせめて`.js`に書く方法があれば嬉しいのですが、まあyamlやjsonでも仕方ないかぁ･･･という気持ちです！

PRのやりとりが長くなっているので、一旦マージしちゃうのもありかもと思いました！
進めやすい方で大丈夫ですので、ぜひチャレンジ頂けると嬉しいです！！

2022-10-17 15:52 UTC, Hiroshiba commented
時間に関しては全く問題ないです！PRとても嬉しいです、ぜひお願いします！！

2022-10-22 02:41 UTC, k-chop commented
遅れてすみません！一通り対応しました。

- モーダル開閉したときSeoコンポーネントの内容が変更されるようにした
- characterKeys, characterInfosをconstantsへ移動
- createPagesの使用をやめcollection routesを使うようにした



> 別にjsonやyamlに書くと型が消えちゃって、タイポしてても気づかないんですよね･･･。
もし.tsかせめて.jsに書く方法があれば嬉しいのですが、まあyamlやjsonでも仕方ないかぁ･･･という気持ちです！

結局 `gatsby-node.ts` の [sourceNodes API](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#sourceNodes) を利用して [graphqlにキャラクターデータを流すように](https://github.com/VOICEVOX/voicevox_blog/pull/102/commits/306e10cb6015779475fae5ec15c8eaec5a6bcd4d) しました！
`src/constants.ts` に定義されたkeys, infosがマスタになるので、typoの心配はなくなります。

ただしgatsby環境起動時にgraphqlへデータを流し込むため、 `npm run develop` 中に `constants.ts` を変更しても反映されないことにご注意ください（注意事項としてコメント書いておきました）

2022-10-22 02:42 UTC, k-chop commented
また、ちょっとこのPR内でやるのは過剰だったかもしれませんが、、、
片方のidを変更してもう片方を忘れるというのを https://github.com/VOICEVOX/voicevox_blog/pull/102/commits/92d398846f13870f84c7eaf96c07638b79ec2d91 で実演してしまったので、
name等重複して現れていた情報はマスタから取ってくるようにして、typoやコピペミスが入りづらいようにしました
ref: https://github.com/VOICEVOX/voicevox_blog/pull/102/commits/f6ba1139a2d77b9aa5ad360b93d401cdc749bfab

2022-10-22 13:58 UTC, Hiroshiba reviewed
ありがとうございます！！

ちょっと１個気になったので、知っていたらお伺いしたく･･･！
今domitoryページとキャラページの移動は、javascriptでhistoryを変える形だと思うのですが、これってクローラーにとってページの親子構造が認識されないとかあるのでしょうか 👀

たぶんjavascriptでのページ移動だと、`/domitory`と`/domitory/zundamon`が親子関係にあることが伝わらないとかあるのかなぁと。
であれば、`<a href="">`で移動する形にしたほうが本当は良いのかなぁと思った次第です。

ただ修正は大変そうなのかなと思うのと、そこまで致命的な問題ではない気もするので、今のPRでマージ＆デプロイするのが良いのかなと思っています。
もし変更したほうが良さそう＆簡単そうなのであれば、お願いできればと思ってお伺いしました！
（k-chopさんが他に取り組みたいissueや提案などあれば、そちらをお願いできればと考えています･･･！）

2022-10-22 13:58 UTC, Hiroshiba commented on gatsby-node.ts
> +    actions.createNode(node)
graphqlへの追加ってこうやるんですね！！
このあたりってやり方はどこで知りましたか？👀
（gatsbyのドキュメントを読むのが結構難しいので、どうやって知ったのか知りたいなーと）

2022-10-22 16:02 UTC, k-chop commented
> 今domitoryページとキャラページの移動は、javascriptでhistoryを変える形だと思うのですが、これってクローラーにとってページの親子構造が認識されないとかあるのでしょうか 👀

ア！！！！これはあると思います。
個別ページにはどこからもリンクが張られていないので、最悪クローラーが見つけられない可能性もありますね・・・
sitemap.xmlなどでクローリング対象を明示することもできますが、親子構造は指定できなさそうです。

同一ページでモーダル開閉ではなくaタグでページ遷移する形にする、で問題なければそんなに苦労せず対応可能ですが、差分が多めにはなりますね・・・
個別のurlを与えてtwitter等で共有できるように、という目的は達成できていると思うので
いったんこの状態でマージしていただいてもよいでしょうか？ 🙇 （やりとり長くなっててすみません）

マージ後aタグでのリンクにするPR出そうと思います

2022-10-22 16:04 UTC, k-chop commented on gatsby-node.ts
> +    actions.createNode(node)
このあたりを読んでいて、
https://www.gatsbyjs.com/docs/how-to/sourcing-data/
graphqlにデータを登録して読めるようにしてるのは `gatsby-source-****` というプラグインということがわかる
↓
プラグインの中で登録してるならその処理内容が分かればいいので
プラグインを自作する場合のドキュメントに当たる
https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/creating-a-source-plugin/
↓
わざわざ自作カスタムプラグイン用意しないといけないの重すぎでは？
例ではsourcenodesを使ってるけどこのAPIで登録してるんだろうか「gatsby sourcenodes」っと
↓
この記事を見つけてgatsby-node内で追加できることを知る
https://qiita.com/abouch/items/ab7694e64f011ee2b265#%E8%87%AA%E5%88%86%E3%81%A7%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

という感じでした
読むの難しいのは確かに・・・
公式ドキュメント読んでる時間長かった（その割に必要な情報見つけられなかった）ですね・・・

2022-10-22 21:12 UTC, Hiroshiba commented on gatsby-node.ts
> +    actions.createNode(node)
なるほど〜〜〜。詳細にありがとうございます。

普通に便利なので公式からサポートがあっても良いのにと少し思いました。
まあでもコード書かずにブログ書けるのがモチベな気がするし、今回みたいな目的は珍しいかもですかねぇ…。

2022-10-22 21:16 UTC, Hiroshiba reviewed
あーー、たしかに見つけられない可能性もありますね。。

一旦マージ、賛成です！aタグにするプルリクとてもありがたいです！！
いったんデプロイはせず、aタグ化してからのデプロイを考えています。

2022-10-22 21:17 UTC, Hiroshiba approved these changes
LGTM！！

2022-10-22 21:17 UTC, merged

2022-10-23 01:04 UTC, k-chop commented
レビューありがとうございました！！引き続きaタグ化進めていきます